% Generated by prolog-star-kb mine-shapes. Do not hand-edit.
% Candidate fact-shape/ontology evidence mined from canonical StarIntel JSON;
% deterministic rebuildable output, not trusted truth. No timestamps are recorded.
% Miner version 1 over 6 documents.
star_shape_manifest('1', '0a09e9e013ebd1d321c217c0e6f5e9def6b7e67cb8af6d4d56dac8239fc99b8e', 6, 3).
star_dtype_count('org', 1).
star_dtype_count('person', 2).
star_dtype_count('relation', 3).
star_field_shape('org', '/_id', 'string', 1, 1).
star_field_cardinality('org', '/_id', 1, 1).
star_field_exemplar('org', '/_id', 'starintel:org:analytical-engines').
star_field_shape('org', '/data/canonical_name', 'string', 1, 1).
star_field_cardinality('org', '/data/canonical_name', 1, 1).
star_field_exemplar('org', '/data/canonical_name', 'starintel:org:analytical-engines').
star_field_shape('org', '/data/headquarters_location', 'string', 1, 1).
star_field_cardinality('org', '/data/headquarters_location', 1, 1).
star_field_exemplar('org', '/data/headquarters_location', 'starintel:org:analytical-engines').
star_field_shape('org', '/dataset', 'string', 1, 1).
star_field_cardinality('org', '/dataset', 1, 1).
star_field_exemplar('org', '/dataset', 'starintel:org:analytical-engines').
star_field_shape('org', '/date_added', 'string', 1, 1).
star_field_cardinality('org', '/date_added', 1, 1).
star_field_exemplar('org', '/date_added', 'starintel:org:analytical-engines').
star_field_shape('org', '/dtype', 'string', 1, 1).
star_field_cardinality('org', '/dtype', 1, 1).
star_field_exemplar('org', '/dtype', 'starintel:org:analytical-engines').
star_field_shape('org', '/schema_version', 'string', 1, 1).
star_field_cardinality('org', '/schema_version', 1, 1).
star_field_exemplar('org', '/schema_version', 'starintel:org:analytical-engines').
star_field_shape('org', '/sources/#/credibility', 'number', 1, 1).
star_field_cardinality('org', '/sources/#/credibility', 1, 1).
star_field_exemplar('org', '/sources/#/credibility', 'starintel:org:analytical-engines').
star_field_shape('org', '/sources/#/kind', 'string', 1, 1).
star_field_cardinality('org', '/sources/#/kind', 1, 1).
star_field_exemplar('org', '/sources/#/kind', 'starintel:org:analytical-engines').
star_field_shape('org', '/sources/#/source_id', 'string', 1, 1).
star_field_cardinality('org', '/sources/#/source_id', 1, 1).
star_field_exemplar('org', '/sources/#/source_id', 'starintel:org:analytical-engines').
star_field_shape('org', '/sources/#/uri', 'string', 1, 1).
star_field_cardinality('org', '/sources/#/uri', 1, 1).
star_field_exemplar('org', '/sources/#/uri', 'starintel:org:analytical-engines').
star_field_shape('org', '/version', 'integer', 1, 1).
star_field_cardinality('org', '/version', 1, 1).
star_field_exemplar('org', '/version', 'starintel:org:analytical-engines').
star_field_shape('person', '/_id', 'string', 2, 2).
star_field_cardinality('person', '/_id', 1, 1).
star_field_exemplar('person', '/_id', 'starintel:person:ada').
star_field_exemplar('person', '/_id', 'starintel:person:grace').
star_field_shape('person', '/data/canonical_name', 'string', 2, 2).
star_field_cardinality('person', '/data/canonical_name', 1, 1).
star_field_exemplar('person', '/data/canonical_name', 'starintel:person:ada').
star_field_exemplar('person', '/data/canonical_name', 'starintel:person:grace').
star_field_shape('person', '/data/employer', 'string', 2, 2).
star_field_cardinality('person', '/data/employer', 1, 1).
star_field_exemplar('person', '/data/employer', 'starintel:person:ada').
star_field_exemplar('person', '/data/employer', 'starintel:person:grace').
star_field_shape('person', '/data/external_ids/#/id', 'string', 1, 1).
star_field_cardinality('person', '/data/external_ids/#/id', 1, 1).
star_field_exemplar('person', '/data/external_ids/#/id', 'starintel:person:ada').
star_field_shape('person', '/data/external_ids/#/platform', 'string', 1, 1).
star_field_cardinality('person', '/data/external_ids/#/platform', 1, 1).
star_field_exemplar('person', '/data/external_ids/#/platform', 'starintel:person:ada').
star_field_shape('person', '/dataset', 'string', 2, 2).
star_field_cardinality('person', '/dataset', 1, 1).
star_field_exemplar('person', '/dataset', 'starintel:person:ada').
star_field_exemplar('person', '/dataset', 'starintel:person:grace').
star_field_shape('person', '/date_added', 'string', 2, 2).
star_field_cardinality('person', '/date_added', 1, 1).
star_field_exemplar('person', '/date_added', 'starintel:person:ada').
star_field_exemplar('person', '/date_added', 'starintel:person:grace').
star_field_shape('person', '/dtype', 'string', 2, 2).
star_field_cardinality('person', '/dtype', 1, 1).
star_field_exemplar('person', '/dtype', 'starintel:person:ada').
star_field_exemplar('person', '/dtype', 'starintel:person:grace').
star_field_shape('person', '/evidence/#/confidence', 'number', 1, 1).
star_field_cardinality('person', '/evidence/#/confidence', 1, 1).
star_field_exemplar('person', '/evidence/#/confidence', 'starintel:person:ada').
star_field_shape('person', '/evidence/#/observation', 'string', 1, 1).
star_field_cardinality('person', '/evidence/#/observation', 1, 1).
star_field_exemplar('person', '/evidence/#/observation', 'starintel:person:ada').
star_field_shape('person', '/evidence/#/role', 'string', 1, 1).
star_field_cardinality('person', '/evidence/#/role', 1, 1).
star_field_exemplar('person', '/evidence/#/role', 'starintel:person:ada').
star_field_shape('person', '/evidence/#/source_url', 'string', 1, 1).
star_field_cardinality('person', '/evidence/#/source_url', 1, 1).
star_field_exemplar('person', '/evidence/#/source_url', 'starintel:person:ada').
star_field_shape('person', '/evidence/#/status', 'string', 1, 1).
star_field_cardinality('person', '/evidence/#/status', 1, 1).
star_field_exemplar('person', '/evidence/#/status', 'starintel:person:ada').
star_field_shape('person', '/posted_at', 'string', 1, 1).
star_field_cardinality('person', '/posted_at', 1, 1).
star_field_exemplar('person', '/posted_at', 'starintel:person:grace').
star_field_shape('person', '/provenance/collector', 'string', 1, 1).
star_field_cardinality('person', '/provenance/collector', 1, 1).
star_field_exemplar('person', '/provenance/collector', 'starintel:person:ada').
star_field_shape('person', '/provenance/run_id', 'string', 1, 1).
star_field_cardinality('person', '/provenance/run_id', 1, 1).
star_field_exemplar('person', '/provenance/run_id', 'starintel:person:ada').
star_field_shape('person', '/schema_version', 'string', 2, 2).
star_field_cardinality('person', '/schema_version', 1, 1).
star_field_exemplar('person', '/schema_version', 'starintel:person:ada').
star_field_exemplar('person', '/schema_version', 'starintel:person:grace').
star_field_shape('person', '/sources/#/credibility', 'number', 3, 2).
star_field_cardinality('person', '/sources/#/credibility', 1, 2).
star_field_exemplar('person', '/sources/#/credibility', 'starintel:person:ada').
star_field_exemplar('person', '/sources/#/credibility', 'starintel:person:grace').
star_field_shape('person', '/sources/#/kind', 'string', 3, 2).
star_field_cardinality('person', '/sources/#/kind', 1, 2).
star_field_exemplar('person', '/sources/#/kind', 'starintel:person:ada').
star_field_exemplar('person', '/sources/#/kind', 'starintel:person:grace').
star_field_shape('person', '/sources/#/reliability', 'number', 1, 1).
star_field_cardinality('person', '/sources/#/reliability', 1, 1).
star_field_exemplar('person', '/sources/#/reliability', 'starintel:person:ada').
star_field_shape('person', '/sources/#/source_id', 'string', 2, 2).
star_field_cardinality('person', '/sources/#/source_id', 1, 1).
star_field_exemplar('person', '/sources/#/source_id', 'starintel:person:ada').
star_field_exemplar('person', '/sources/#/source_id', 'starintel:person:grace').
star_field_shape('person', '/sources/#/title', 'string', 1, 1).
star_field_cardinality('person', '/sources/#/title', 1, 1).
star_field_exemplar('person', '/sources/#/title', 'starintel:person:ada').
star_field_shape('person', '/sources/#/uri', 'string', 3, 2).
star_field_cardinality('person', '/sources/#/uri', 1, 2).
star_field_exemplar('person', '/sources/#/uri', 'starintel:person:ada').
star_field_exemplar('person', '/sources/#/uri', 'starintel:person:grace').
star_field_shape('person', '/version', 'integer', 2, 2).
star_field_cardinality('person', '/version', 1, 1).
star_field_exemplar('person', '/version', 'starintel:person:ada').
star_field_exemplar('person', '/version', 'starintel:person:grace').
star_field_shape('relation', '/_id', 'string', 3, 3).
star_field_cardinality('relation', '/_id', 1, 1).
star_field_exemplar('relation', '/_id', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/_id', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/_id', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/confidence', 'number', 1, 1).
star_field_cardinality('relation', '/data/confidence', 1, 1).
star_field_exemplar('relation', '/data/confidence', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/data/directed', 'boolean', 3, 3).
star_field_cardinality('relation', '/data/directed', 1, 1).
star_field_exemplar('relation', '/data/directed', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/data/directed', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/data/directed', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/object', 'string', 1, 1).
star_field_cardinality('relation', '/data/object', 1, 1).
star_field_exemplar('relation', '/data/object', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/data/object/dtype', 'string', 1, 1).
star_field_cardinality('relation', '/data/object/dtype', 1, 1).
star_field_exemplar('relation', '/data/object/dtype', 'starintel:relation:ada-member-of-ae').
star_field_shape('relation', '/data/object/entity_id', 'string', 1, 1).
star_field_cardinality('relation', '/data/object/entity_id', 1, 1).
star_field_exemplar('relation', '/data/object/entity_id', 'starintel:relation:ada-member-of-ae').
star_field_shape('relation', '/data/object/external_id', 'string', 1, 1).
star_field_cardinality('relation', '/data/object/external_id', 1, 1).
star_field_exemplar('relation', '/data/object/external_id', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/object/label', 'string', 1, 1).
star_field_cardinality('relation', '/data/object/label', 1, 1).
star_field_exemplar('relation', '/data/object/label', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/object/unresolved', 'boolean', 2, 2).
star_field_cardinality('relation', '/data/object/unresolved', 1, 1).
star_field_exemplar('relation', '/data/object/unresolved', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/data/object/unresolved', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/predicate', 'string', 3, 3).
star_field_cardinality('relation', '/data/predicate', 1, 1).
star_field_exemplar('relation', '/data/predicate', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/data/predicate', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/data/predicate', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/qualifiers/npa', 'integer', 2, 2).
star_field_cardinality('relation', '/data/qualifiers/npa', 1, 1).
star_field_exemplar('relation', '/data/qualifiers/npa', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/data/qualifiers/npa', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/qualifiers/role', 'string', 1, 1).
star_field_cardinality('relation', '/data/qualifiers/role', 1, 1).
star_field_exemplar('relation', '/data/qualifiers/role', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/data/start_at', 'string', 1, 1).
star_field_cardinality('relation', '/data/start_at', 1, 1).
star_field_exemplar('relation', '/data/start_at', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/data/subject', 'string', 2, 2).
star_field_cardinality('relation', '/data/subject', 1, 1).
star_field_exemplar('relation', '/data/subject', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/data/subject', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/data/subject/dtype', 'string', 1, 1).
star_field_cardinality('relation', '/data/subject/dtype', 1, 1).
star_field_exemplar('relation', '/data/subject/dtype', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/subject/id', 'string', 1, 1).
star_field_cardinality('relation', '/data/subject/id', 1, 1).
star_field_exemplar('relation', '/data/subject/id', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/data/subject/role', 'string', 1, 1).
star_field_cardinality('relation', '/data/subject/role', 1, 1).
star_field_exemplar('relation', '/data/subject/role', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/dataset', 'string', 3, 3).
star_field_cardinality('relation', '/dataset', 1, 1).
star_field_exemplar('relation', '/dataset', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/dataset', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/dataset', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/date_added', 'string', 3, 3).
star_field_cardinality('relation', '/date_added', 1, 1).
star_field_exemplar('relation', '/date_added', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/date_added', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/date_added', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/dtype', 'string', 3, 3).
star_field_cardinality('relation', '/dtype', 1, 1).
star_field_exemplar('relation', '/dtype', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/dtype', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/dtype', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/evidence/#/claim', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/claim', 1, 1).
star_field_exemplar('relation', '/evidence/#/claim', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/confidence', 'number', 1, 1).
star_field_cardinality('relation', '/evidence/#/confidence', 1, 1).
star_field_exemplar('relation', '/evidence/#/confidence', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/evidence_id', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/evidence_id', 1, 1).
star_field_exemplar('relation', '/evidence/#/evidence_id', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/role', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/role', 1, 1).
star_field_exemplar('relation', '/evidence/#/role', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/source_id', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/source_id', 1, 1).
star_field_exemplar('relation', '/evidence/#/source_id', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/source_url', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/source_url', 1, 1).
star_field_exemplar('relation', '/evidence/#/source_url', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/evidence/#/status', 'string', 1, 1).
star_field_cardinality('relation', '/evidence/#/status', 1, 1).
star_field_exemplar('relation', '/evidence/#/status', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/provenance/collector', 'string', 1, 1).
star_field_cardinality('relation', '/provenance/collector', 1, 1).
star_field_exemplar('relation', '/provenance/collector', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/provenance/run_id', 'string', 1, 1).
star_field_cardinality('relation', '/provenance/run_id', 1, 1).
star_field_exemplar('relation', '/provenance/run_id', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/schema_version', 'string', 3, 3).
star_field_cardinality('relation', '/schema_version', 1, 1).
star_field_exemplar('relation', '/schema_version', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/schema_version', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/schema_version', 'starintel:relation:ae-listed-from-npa').
star_field_shape('relation', '/sources/#/credibility', 'number', 1, 1).
star_field_cardinality('relation', '/sources/#/credibility', 1, 1).
star_field_exemplar('relation', '/sources/#/credibility', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/sources/#/kind', 'string', 1, 1).
star_field_cardinality('relation', '/sources/#/kind', 1, 1).
star_field_exemplar('relation', '/sources/#/kind', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/sources/#/source_id', 'string', 1, 1).
star_field_cardinality('relation', '/sources/#/source_id', 1, 1).
star_field_exemplar('relation', '/sources/#/source_id', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/sources/#/uri', 'string', 1, 1).
star_field_cardinality('relation', '/sources/#/uri', 1, 1).
star_field_exemplar('relation', '/sources/#/uri', 'starintel:relation:ada-works-for-ae').
star_field_shape('relation', '/version', 'integer', 3, 3).
star_field_cardinality('relation', '/version', 1, 1).
star_field_exemplar('relation', '/version', 'starintel:relation:ada-member-of-ae').
star_field_exemplar('relation', '/version', 'starintel:relation:ada-works-for-ae').
star_field_exemplar('relation', '/version', 'starintel:relation:ae-listed-from-npa').
star_relation_shape('enumerated_from_area_code', 'org', 'unresolved', 1).
star_relation_shape('member_of', 'person', 'org', 1).
star_relation_shape('works_for', 'person', 'org', 1).
star_qualifier_shape('enumerated_from_area_code', 'npa', 'integer', 1).
star_qualifier_shape('works_for', 'npa', 'integer', 1).
star_qualifier_shape('works_for', 'role', 'string', 1).
star_temporal_key('org', 'date_added', 1).
star_temporal_key('person', 'date_added', 2).
star_temporal_key('person', 'posted_at', 1).
star_temporal_key('relation', 'date_added', 3).
star_temporal_key('relation', 'start_at', 1).
star_ref_shape('person', 'org', 2).
star_ref_shape('relation', 'org', 3).
star_ref_shape('relation', 'person', 2).
